games_data = [
    {"team1": "Atlanta Hawks", "team2": "Boston Celtics", "date": "2023-10-18", "location": "Boston"},
    {"team1": "Miami Heat", "team2": "Los Angeles Lakers", "date": "2023-10-19", "location": "Miami"},
    {"team1": "Chicago Bulls", "team2": "New York Knicks", "date": "2023-10-20", "location": "Chicago"},
    {"team1": "Golden State Warriors", "team2": "Brooklyn Nets", "date": "2023-10-21", "location": "San Francisco"},
    {"team1": "Dallas Mavericks", "team2": "Houston Rockets", "date": "2023-10-22", "location": "Dallas"},
    {"team1": "Philadelphia 76ers", "team2": "Toronto Raptors", "date": "2023-10-23", "location": "Philadelphia"},
    {"team1": "Utah Jazz", "team2": "Denver Nuggets", "date": "2023-10-24", "location": "Salt Lake City"},
    {"team1": "Phoenix Suns", "team2": "Portland Trail Blazers", "date": "2023-10-25", "location": "Phoenix"},
    {"team1": "Indiana Pacers", "team2": "Cleveland Cavaliers", "date": "2023-10-26", "location": "Indianapolis"},
    {"team1": "Memphis Grizzlies", "team2": "San Antonio Spurs", "date": "2023-10-27", "location": "Memphis"},
    {"team1": "Milwaukee Bucks", "team2": "Orlando Magic", "date": "2023-10-28", "location": "Milwaukee"},
    {"team1": "Detroit Pistons", "team2": "Charlotte Hornets", "date": "2023-10-29", "location": "Detroit"},
    {"team1": "Oklahoma City Thunder", "team2": "Minnesota Timberwolves", "date": "2023-10-30", "location": "Oklahoma City"},
    {"team1": "Los Angeles Clippers", "team2": "Sacramento Kings", "date": "2023-10-31", "location": "Los Angeles"},
    {"team1": "New Orleans Pelicans", "team2": "Washington Wizards", "date": "2023-11-01", "location": "New Orleans"},
    {"team1": "Boston Celtics", "team2": "Miami Heat", "date": "2023-11-02", "location": "Boston"},
    {"team1": "Brooklyn Nets", "team2": "Philadelphia 76ers", "date": "2023-11-03", "location": "Brooklyn"},
    {"team1": "Houston Rockets", "team2": "Dallas Mavericks", "date": "2023-11-04", "location": "Houston"},
    {"team1": "Portland Trail Blazers", "team2": "Golden State Warriors", "date": "2023-11-05", "location": "Portland"},
    {"team1": "Toronto Raptors", "team2": "Chicago Bulls", "date": "2023-11-06", "location": "Toronto"},
]
