team_data = [
    {
        "id": 1,
        "name": "Atlanta Hawks",
        "roster": [
            {"name": "Nickeil Alexander-Walker", "position": "G", "height": "6-5", "weight": "205 lbs", "last_attended": "Virginia Tech", "country": "Canada"},
            {"name": "Dyson Daniels", "position": "G", "height": "6-7", "weight": "199 lbs", "last_attended": "NBA G League Ignite", "country": "Australia"},
            {"name": "N'Faly Dante", "position": "C", "height": "6-11", "weight": "230 lbs", "last_attended": "Oregon", "country": "Mali"},
            {"name": "Nikola Đurišić", "position": "G", "height": "6-8", "weight": "214 lbs", "last_attended": "Mega Basket", "country": "Belgium"},
            {"name": "Mouhamed Gueye", "position": "F", "height": "6-11", "weight": "210 lbs", "last_attended": "Washington State", "country": "Senegal"},
            {"name": "Caleb Houstan", "position": "G", "height": "6-8", "weight": "205 lbs", "last_attended": "Michigan", "country": "Canada"},
            {"name": "Jalen Johnson", "position": "F", "height": "6-8", "weight": "219 lbs", "last_attended": "Duke", "country": "USA"},
            {"name": "Luke Kennard", "position": "G", "height": "6-5", "weight": "206 lbs", "last_attended": "Duke", "country": "USA"},
            {"name": "Vít Krejčí", "position": "G", "height": "6-8", "weight": "195 lbs", "last_attended": "Zaragoza", "country": "Czech Republic"},
            {"name": "Eli John Ndiaye", "position": "F", "height": "6-8", "weight": "209 lbs", "last_attended": "Real Madrid", "country": "Senegal"},
            {"name": "Asa Newell", "position": "F", "height": "6-10", "weight": "220 lbs", "last_attended": "Georgia", "country": "USA"},
            {"name": "Onyeka Okongwu", "position": "F-C", "height": "6-10", "weight": "240 lbs", "last_attended": "Southern California", "country": "USA"},
            {"name": "Kristaps Porziņģis", "position": "F-C", "height": "7-2", "weight": "240 lbs", "last_attended": "Cajasol Sevilla", "country": "Latvia"},
            {"name": "Zaccharie Risacher", "position": "F", "height": "6-8", "weight": "200 lbs", "last_attended": "JL Bourg-en-Bresse", "country": "France"},
            {"name": "Jacob Toppin", "position": "F", "height": "6-9", "weight": "200 lbs", "last_attended": "Kentucky", "country": "USA"},
            {"name": "Keaton Wallace", "position": "G", "height": "6-3", "weight": "185 lbs", "last_attended": "Texas-San Antonio", "country": "USA"},
            {"name": "Trae Young", "position": "G", "height": "6-2", "weight": "164 lbs", "last_attended": "Oklahoma", "country": "USA"},
        ]
    },
    {
        "id": 2,
        "name": "Boston Celtics",
        "roster": [
            {"name": "Chris Boucher", "position": "F", "height": "6-8", "weight": "200 lbs", "last_attended": "Oregon", "country": "Saint Lucia"},
            {"name": "Jaylen Brown", "position": "G-F", "height": "6-6", "weight": "223 lbs", "last_attended": "California", "country": "USA"},
            {"name": "Luka Garza", "position": "C", "height": "6-10", "weight": "243 lbs", "last_attended": "Iowa", "country": "USA"},
            {"name": "Hugo González", "position": "G", "height": "6-6", "weight": "200 lbs", "last_attended": "Real Madrid", "country": "Spain"},
            {"name": "Ron Harper Jr.", "position": "G-F", "height": "6-5", "weight": "233 lbs", "last_attended": "Rutgers", "country": "USA"},
            {"name": "Sam Hauser", "position": "F", "height": "6-7", "weight": "217 lbs", "last_attended": "Virginia", "country": "USA"},
            {"name": "Josh Minott", "position": "F", "height": "6-8", "weight": "205 lbs", "last_attended": "Memphis", "country": "USA"},
            {"name": "Payton Pritchard", "position": "G", "height": "6-1", "weight": "195 lbs", "last_attended": "Oregon", "country": "USA"},
            {"name": "Neemias Queta", "position": "C", "height": "7-0", "weight": "248 lbs", "last_attended": "Utah State", "country": "Portugal"},
            {"name": "Baylor Scheierman", "position": "G", "height": "6-6", "weight": "205 lbs", "last_attended": "Creighton", "country": "USA"},
            {"name": "Max Shulga", "position": "G", "height": "6-4", "weight": "210 lbs", "last_attended": "Virginia Commonwealth", "country": "Ukraine"},
            {"name": "Anfernee Simons", "position": "G", "height": "6-3", "weight": "200 lbs", "last_attended": "Edgewater HS (FL)", "country": "USA"},
            {"name": "Jayson Tatum", "position": "F-G", "height": "6-8", "weight": "210 lbs", "last_attended": "Duke", "country": "USA"},
            {"name": "Xavier Tillman", "position": "F", "height": "6-8", "weight": "245 lbs", "last_attended": "Michigan State", "country": "USA"},
            {"name": "Jordan Walsh", "position": "G", "height": "6-6", "weight": "205 lbs", "last_attended": "Arkansas", "country": "USA"},
            {"name": "Derrick White", "position": "G", "height": "6-4", "weight": "190 lbs", "last_attended": "Colorado", "country": "USA"},
            {"name": "Amari Williams", "position": "F-C", "height": "6-11", "weight": "250 lbs", "last_attended": "Kentucky", "country": "United Kingdom"},
        ]
    },
    {
        "id": 3,
        "name": "Brooklyn Nets",
        "roster": [
            {"name": "Nic Claxton", "position": "C", "height": "6-11", "weight": "215 lbs", "last_attended": "Georgia", "country": "USA"},
            {"name": "Noah Clowney", "position": "F-C", "height": "6-10", "weight": "210 lbs", "last_attended": "Alabama", "country": "USA"},
            {"name": "Egor Dëmin", "position": "G", "height": "6-8", "weight": "200 lbs", "last_attended": "Brigham Young", "country": "Russia"},
            {"name": "Tyson Etienne", "position": "G", "height": "6-0", "weight": "200 lbs", "last_attended": "Wichita State", "country": "USA"},
            {"name": "Haywood Highsmith", "position": "F", "height": "6-5", "weight": "220 lbs", "last_attended": "Wheeling Jesuit", "country": "USA"},
            {"name": "E.J. Liddell", "position": "F", "height": "6-6", "weight": "240 lbs", "last_attended": "Ohio State", "country": "USA"},
            {"name": "Terance Mann", "position": "G-F", "height": "6-6", "weight": "215 lbs", "last_attended": "Florida State", "country": "USA"},
            {"name": "Tyrese Martin", "position": "F", "height": "6-6", "weight": "215 lbs", "last_attended": "Connecticut", "country": "USA"},
            {"name": "Michael Porter Jr.", "position": "F", "height": "6-10", "weight": "218 lbs", "last_attended": "Missouri", "country": "USA"},
            {"name": "Drake Powell", "position": "G-F", "height": "6-5", "weight": "195 lbs", "last_attended": "North Carolina", "country": "USA"},
            {"name": "Ben Saraf", "position": "G", "height": "6-6", "weight": "200 lbs", "last_attended": "Ratiopharm Ulm", "country": "Israel"},
            {"name": "Day'Ron Sharpe", "position": "C", "height": "6-10", "weight": "265 lbs", "last_attended": "North Carolina", "country": "USA"},
            {"name": "Cam Thomas", "position": "G", "height": "6-3", "weight": "210 lbs", "last_attended": "Louisiana State", "country": "Japan"},
            {"name": "Nolan Traore", "position": "G", "height": "6-3", "weight": "185 lbs", "last_attended": "Saint-Quentin", "country": "France"},
            {"name": "Ziaire Williams", "position": "F", "height": "6-9", "weight": "185 lbs", "last_attended": "Stanford", "country": "USA"},
            {"name": "Jalen Wilson", "position": "F", "height": "6-6", "weight": "220 lbs", "last_attended": "Kansas", "country": "USA"},
            {"name": "Danny Wolf", "position": "F", "height": "6-11", "weight": "250 lbs", "last_attended": "Michigan", "country": "USA"},
        ]
    },
    {
        "id": 4,
        "name": "Charlotte Hornets",
        "roster": [
            {"name": "LaMelo Ball", "position": "G", "height": "6-7", "weight": "180 lbs", "last_attended": "Illawarra", "country": "USA"},
            {"name": "Miles Bridges", "position": "F", "height": "6-7", "weight": "225 lbs", "last_attended": "Michigan State", "country": "USA"},
            {"name": "Pat Connaughton", "position": "G", "height": "6-5", "weight": "209 lbs", "last_attended": "Notre Dame", "country": "USA"},
            {"name": "Moussa Diabaté", "position": "F", "height": "6-10", "weight": "210 lbs", "last_attended": "Michigan", "country": "France"},
            {"name": "Josh Green", "position": "G", "height": "6-6", "weight": "200 lbs", "last_attended": "Arizona", "country": "Australia"},
            {"name": "Sion James", "position": "G", "height": "6-5", "weight": "220 lbs", "last_attended": "Duke", "country": "USA"},
            {"name": "Ryan Kalkbrenner", "position": "C", "height": "7-1", "weight": "256 lbs", "last_attended": "Creighton", "country": "USA"},
            {"name": "Kon Knueppel", "position": "G-F", "height": "6-6", "weight": "215 lbs", "last_attended": "Duke", "country": "USA"},
            {"name": "Tre Mann", "position": "G", "height": "6-4", "weight": "178 lbs", "last_attended": "Florida", "country": "USA"},
            {"name": "Liam McNeeley", "position": "F", "height": "6-7", "weight": "210 lbs", "last_attended": "Connecticut", "country": "USA"},
            {"name": "Brandon Miller", "position": "F", "height": "6-7", "weight": "200 lbs", "last_attended": "Alabama", "country": "USA"},
            {"name": "Drew Peterson", "position": "F", "height": "6-8", "weight": "205 lbs", "last_attended": "Southern California", "country": "USA"},
            {"name": "Mason Plumlee", "position": "F-C", "height": "7-0", "weight": "254 lbs", "last_attended": "Duke", "country": "USA"},
            {"name": "Antonio Reeves", "position": "G", "height": "6-5", "weight": "205 lbs", "last_attended": "Kentucky", "country": "USA"},
            {"name": "Tidjane Salaün", "position": "F", "height": "6-10", "weight": "207 lbs", "last_attended": "Cholet", "country": "France"},
            {"name": "Collin Sexton", "position": "G", "height": "6-3", "weight": "190 lbs", "last_attended": "Alabama", "country": "USA"},
            {"name": "KJ Simpson", "position": "G", "height": "6-2", "weight": "189 lbs", "last_attended": "Colorado", "country": "USA"},
            {"name": "Grant Williams", "position": "F", "height": "6-7", "weight": "236 lbs", "last_attended": "Tennessee", "country": "USA"},
        ]
    },
    {
        "id": 5,
        "name": "Chicago Bulls",
        "roster": [
            {"name": "Matas Buzelis", "position": "F", "height": "6-8", "weight": "209 lbs", "last_attended": "NBA G League Ignite", "country": "USA"},
            {"name": "Jevon Carter", "position": "G", "height": "6-0", "weight": "200 lbs", "last_attended": "West Virginia", "country": "USA"},
            {"name": "Zach Collins", "position": "F-C", "height": "6-9", "weight": "250 lbs", "last_attended": "Gonzaga", "country": "USA"},
            {"name": "Ayo Dosunmu", "position": "G", "height": "6-4", "weight": "200 lbs", "last_attended": "Illinois", "country": "USA"},
            {"name": "Noa Essengue", "position": "F", "height": "6-8", "weight": "200 lbs", "last_attended": "-", "country": "France"},
            {"name": "Trentyn Flowers", "position": "F", "height": "6-9", "weight": "185 lbs", "last_attended": "Adelaide", "country": "USA"},
            {"name": "Josh Giddey", "position": "G", "height": "6-7", "weight": "216 lbs", "last_attended": "NBA Global Academy", "country": "Australia"},
            {"name": "Kevin Huerter", "position": "G-F", "height": "6-6", "weight": "198 lbs", "last_attended": "Maryland", "country": "USA"},
            {"name": "Tre Jones", "position": "G", "height": "6-1", "weight": "185 lbs", "last_attended": "Duke", "country": "USA"},
            {"name": "Emanuel Miller", "position": "F", "height": "6-5", "weight": "215 lbs", "last_attended": "TCU", "country": "Canada"},
            {"name": "Isaac Okoro", "position": "F-G", "height": "6-4", "weight": "225 lbs", "last_attended": "Auburn", "country": "USA"},
            {"name": "Lachlan Olbrich", "position": "C", "height": "6-8", "weight": "236 lbs", "last_attended": "Illawarra", "country": "Australia"},
            {"name": "Julian Phillips", "position": "F", "height": "6-6", "weight": "198 lbs", "last_attended": "Tennessee", "country": "USA"},
            {"name": "Jalen Smith", "position": "F-C", "height": "6-8", "weight": "215 lbs", "last_attended": "Maryland", "country": "USA"},
            {"name": "Dalen Terry", "position": "F", "height": "6-6", "weight": "195 lbs", "last_attended": "Arizona", "country": "USA"},
            {"name": "Nikola Vučević", "position": "C", "height": "6-9", "weight": "260 lbs", "last_attended": "Southern California", "country": "Montenegro"},
            {"name": "Coby White", "position": "G", "height": "6-4", "weight": "195 lbs", "last_attended": "North Carolina", "country": "USA"},
            {"name": "Patrick Williams", "position": "F", "height": "6-6", "weight": "215 lbs", "last_attended": "Florida State", "country": "USA"},
        ]
    },
    {
        "id": 6,
        "name": "Cleveland Cavaliers",
        "roster": [
            {"name": "Jarrett Allen", "position": "C", "height": "6-9", "weight": "243 lbs", "last_attended": "Texas", "country": "USA"},
            {"name": "Lonzo Ball", "position": "G", "height": "6-5", "weight": "190 lbs", "last_attended": "UCLA", "country": "USA"},
            {"name": "Thomas Bryant", "position": "C-F", "height": "6-9", "weight": "248 lbs", "last_attended": "Indiana", "country": "USA"},
            {"name": "Darius Garland", "position": "G", "height": "6-1", "weight": "192 lbs", "last_attended": "Vanderbilt", "country": "USA"},
            {"name": "De'Andre Hunter", "position": "F-G", "height": "6-7", "weight": "221 lbs", "last_attended": "Virginia", "country": "USA"},
            {"name": "Chris Livingston", "position": "F", "height": "6-6", "weight": "220 lbs", "last_attended": "Kentucky", "country": "USA"},
            {"name": "Sam Merrill", "position": "G", "height": "6-4", "weight": "205 lbs", "last_attended": "Utah State", "country": "USA"},
            {"name": "Donovan Mitchell", "position": "G", "height": "6-2", "weight": "215 lbs", "last_attended": "Louisville", "country": "USA"},
            {"name": "Evan Mobley", "position": "C", "height": "6-11", "weight": "215 lbs", "last_attended": "Southern California", "country": "USA"},
            {"name": "Larry Nance Jr.", "position": "F-C", "height": "6-6", "weight": "245 lbs", "last_attended": "Wyoming", "country": "USA"},
            {"name": "Craig Porter Jr.", "position": "G", "height": "6-1", "weight": "180 lbs", "last_attended": "Wichita State", "country": "USA"},
            {"name": "Tyrese Proctor", "position": "G", "height": "6-4", "weight": "185 lbs", "last_attended": "Duke", "country": "Australia"},
            {"name": "Max Strus", "position": "G-F", "height": "6-5", "weight": "215 lbs", "last_attended": "DePaul", "country": "USA"},
            {"name": "Nae'Qwan Tomlin", "position": "F", "height": "6-8", "weight": "210 lbs", "last_attended": "Memphis", "country": "USA"},
            {"name": "Luke Travers", "position": "F", "height": "6-6", "weight": "207 lbs", "last_attended": "Rockingham Flames (Aus.)", "country": "Australia"},
            {"name": "Jaylon Tyson", "position": "G-F", "height": "6-6", "weight": "215 lbs", "last_attended": "California", "country": "USA"},
            {"name": "Dean Wade", "position": "F-C", "height": "6-9", "weight": "228 lbs", "last_attended": "Kansas State", "country": "USA"},
        ]
    },
    {
        "id": 7,
        "name": "Dallas Mavericks",
        "roster": [
            {"name": "Max Christie", "position": "G", "height": "6-5", "weight": "190 lbs", "last_attended": "Michigan State", "country": "USA"},
            {"name": "Moussa Cisse", "position": "C", "height": "6-11", "weight": "220 lbs", "last_attended": "Memphis", "country": "Guinea"},
            {"name": "Anthony Davis", "position": "F-C", "height": "6-10", "weight": "253 lbs", "last_attended": "Kentucky", "country": "USA"},
            {"name": "Danté Exum", "position": "G", "height": "6-5", "weight": "214 lbs", "last_attended": "Australian Institute of Sport", "country": "Australia"},
            {"name": "Cooper Flagg", "position": "F", "height": "6-9", "weight": "205 lbs", "last_attended": "Duke", "country": "USA"},
            {"name": "Daniel Gafford", "position": "F-C", "height": "6-10", "weight": "265 lbs", "last_attended": "Arkansas", "country": "USA"},
            {"name": "Jaden Hardy", "position": "G", "height": "6-3", "weight": "198 lbs", "last_attended": "NBA G League Ignite", "country": "USA"},
            {"name": "Kyrie Irving", "position": "G", "height": "6-2", "weight": "195 lbs", "last_attended": "Duke", "country": "Australia"},
            {"name": "Miles Kelly", "position": "G", "height": "6-4", "weight": "190 lbs", "last_attended": "Auburn", "country": "USA"},
            {"name": "Dereck Lively II", "position": "C", "height": "7-1", "weight": "230 lbs", "last_attended": "Duke", "country": "USA"},
            {"name": "Naji Marshall", "position": "F", "height": "6-6", "weight": "220 lbs", "last_attended": "Xavier", "country": "USA"},
            {"name": "Caleb Martin", "position": "F", "height": "6-5", "weight": "205 lbs", "last_attended": "Nevada", "country": "USA"},
            {"name": "Ryan Nembhard", "position": "G", "height": "5-11", "weight": "180 lbs", "last_attended": "Gonzaga", "country": "Canada"},
            {"name": "Dwight Powell", "position": "F-C", "height": "6-10", "weight": "240 lbs", "last_attended": "Stanford", "country": "Canada"},
            {"name": "D'Angelo Russell", "position": "G", "height": "6-3", "weight": "193 lbs", "last_attended": "Ohio State", "country": "USA"},
            {"name": "Klay Thompson", "position": "G", "height": "6-5", "weight": "220 lbs", "last_attended": "Washington State", "country": "USA"},
            {"name": "P.J. Washington", "position": "F", "height": "6-7", "weight": "230 lbs", "last_attended": "Kentucky", "country": "USA"},
            {"name": "Brandon Williams", "position": "G", "height": "6-1", "weight": "190 lbs", "last_attended": "Arizona", "country": "USA"},
        ]
    },
    {
        "id": 8,
        "name": "Denver Nuggets",
        "roster": [
            {"name": "Tamar Bates", "position": "G", "height": "6-4", "weight": "195 lbs", "last_attended": "Missouri", "country": "USA"},
            {"name": "Christian Braun", "position": "G", "height": "6-6", "weight": "220 lbs", "last_attended": "Kansas", "country": "USA"},
            {"name": "Bruce Brown", "position": "G-F", "height": "6-4", "weight": "202 lbs", "last_attended": "Miami", "country": "USA"},
            {"name": "Aaron Gordon", "position": "F", "height": "6-8", "weight": "235 lbs", "last_attended": "Arizona", "country": "USA"},
            {"name": "Tim Hardaway Jr.", "position": "G-F", "height": "6-5", "weight": "205 lbs", "last_attended": "Michigan", "country": "USA"},
            {"name": "DaRon Holmes II", "position": "F", "height": "6-9", "weight": "225 lbs", "last_attended": "Dayton", "country": "USA"},
            {"name": "Cameron Johnson", "position": "F", "height": "6-8", "weight": "210 lbs", "last_attended": "North Carolina", "country": "USA"},
            {"name": "Nikola Jokić", "position": "C", "height": "6-11", "weight": "284 lbs", "last_attended": "Mega Basket", "country": "Serbia"},
            {"name": "Curtis Jones", "position": "G", "height": "6-3", "weight": "195 lbs", "last_attended": "Iowa State", "country": "USA"},
            {"name": "Spencer Jones", "position": "F", "height": "6-7", "weight": "225 lbs", "last_attended": "Stanford", "country": "USA"},
            {"name": "Jamal Murray", "position": "G", "height": "6-4", "weight": "215 lbs", "last_attended": "Kentucky", "country": "Canada"},
            {"name": "Zeke Nnaji", "position": "F-C", "height": "6-10", "weight": "240 lbs", "last_attended": "Arizona", "country": "USA"},
            {"name": "Jalen Pickett", "position": "G", "height": "6-2", "weight": "202 lbs", "last_attended": "Penn State", "country": "USA"},
            {"name": "Julian Strawther", "position": "F", "height": "6-6", "weight": "205 lbs", "last_attended": "Gonzaga", "country": "USA"},
            {"name": "Hunter Tyson", "position": "F", "height": "6-8", "weight": "215 lbs", "last_attended": "Clemson", "country": "USA"},
            {"name": "Jonas Valančiūnas", "position": "C", "height": "6-11", "weight": "265 lbs", "last_attended": "Lietuvos rytas Vilnius", "country": "Lithuania"},
            {"name": "Peyton Watson", "position": "G", "height": "6-8", "weight": "200 lbs", "last_attended": "UCLA", "country": "USA"},
        ]
    },
    {
        "id": 9,
        "name": "Detroit Pistons",
        "roster": [
            {"name": "Ron Holland II", "position": "F", "height": "6-7", "weight": "206 lbs", "last_attended": "NBA G League Ignite", "country": "USA"},
            {"name": "Cade Cunningham", "position": "G", "height": "6-6", "weight": "220 lbs", "last_attended": "Oklahoma State", "country": "USA"},
            {"name": "Jaden Ivey", "position": "G", "height": "6-4", "weight": "200 lbs", "last_attended": "Purdue", "country": "USA"},
            {"name": "Tobias Harris", "position": "F", "height": "6-7", "weight": "226 lbs", "last_attended": "Tennessee", "country": "USA"},
            {"name": "Tim Hardaway Jr.", "position": "G-F", "height": "6-5", "weight": "205 lbs", "last_attended": "Michigan", "country": "USA"},
            {"name": "Malik Beasley", "position": "G", "height": "6-4", "weight": "187 lbs", "last_attended": "Florida State", "country": "USA"},
            {"name": "Isaiah Stewart", "position": "F-C", "height": "6-8", "weight": "250 lbs", "last_attended": "Washington", "country": "USA"},
            {"name": "Simone Fontecchio", "position": "F", "height": "6-7", "weight": "209 lbs", "last_attended": "Baskonia", "country": "Italy"},
            {"name": "Paul Reed", "position": "F", "height": "6-8", "weight": "210 lbs", "last_attended": "DePaul", "country": "USA"},
            {"name": "Wendell Moore Jr.", "position": "G-F", "height": "6-5", "weight": "215 lbs", "last_attended": "Duke", "country": "USA"},
            {"name": "Ausar Thompson", "position": "G-F", "height": "6-7", "weight": "205 lbs", "last_attended": "Overtime Elite", "country": "USA"},
        ]
    },
    {
        "id": 10,
        "name": "Golden State Warriors",
        "roster": [
            {"name": "Stephen Curry", "position": "G", "height": "6-2", "weight": "185 lbs", "last_attended": "Davidson", "country": "USA"},
            {"name": "Draymond Green", "position": "F", "height": "6-6", "weight": "230 lbs", "last_attended": "Michigan State", "country": "USA"},
            {"name": "Jonathan Kuminga", "position": "F", "height": "6-7", "weight": "210 lbs", "last_attended": "NBA G League Ignite", "country": "Congo"},
            {"name": "Kevon Looney", "position": "C-F", "height": "6-9", "weight": "222 lbs", "last_attended": "UCLA", "country": "USA"},
            {"name": "Moses Moody", "position": "G", "height": "6-5", "weight": "211 lbs", "last_attended": "Arkansas", "country": "USA"},
            {"name": "Brandin Podziemski", "position": "G", "height": "6-4", "weight": "205 lbs", "last_attended": "Santa Clara", "country": "USA"},
            {"name": "Gary Payton II", "position": "G", "height": "6-2", "weight": "195 lbs", "last_attended": "Oregon State", "country": "USA"},
            {"name": "Trayce Jackson-Davis", "position": "F-C", "height": "6-9", "weight": "245 lbs", "last_attended": "Indiana", "country": "USA"},
            {"name": "Dennis Schröder", "position": "G", "height": "6-1", "weight": "175 lbs", "last_attended": "Braunschweig", "country": "Germany"},
            {"name": "Buddy Hield", "position": "G-F", "height": "6-4", "weight": "220 lbs", "last_attended": "Oklahoma", "country": "Bahamas"},
            {"name": "Kyle Anderson", "position": "F-G", "height": "6-8", "weight": "230 lbs", "last_attended": "UCLA", "country": "USA"},
        ]
    },
    {
        "id": 11,
        "name": "Houston Rockets",
        "roster": [
            {"name": "Alperen Şengün", "position": "C", "height": "6-10", "weight": "243 lbs", "last_attended": "Besiktas", "country": "Turkey"},
            {"name": "Jalen Green", "position": "G", "height": "6-4", "weight": "186 lbs", "last_attended": "NBA G League Ignite", "country": "USA"},
            {"name": "Amen Thompson", "position": "G-F", "height": "6-6", "weight": "209 lbs", "last_attended": "Overtime Elite", "country": "USA"},
            {"name": "Jabari Smith Jr.", "position": "F-C", "height": "6-10", "weight": "225 lbs", "last_attended": "Auburn", "country": "USA"},
            {"name": "Dillon Brooks", "position": "G-F", "height": "6-6", "weight": "225 lbs", "last_attended": "Oregon", "country": "Canada"},
            {"name": "Fred VanVleet", "position": "G", "height": "6-0", "weight": "197 lbs", "last_attended": "Wichita State", "country": "USA"},
            {"name": "Steven Adams", "position": "C", "height": "6-11", "weight": "265 lbs", "last_attended": "Pittsburgh", "country": "New Zealand"},
            {"name": "Tari Eason", "position": "F", "height": "6-7", "weight": "216 lbs", "last_attended": "Louisiana State", "country": "USA"},
            {"name": "Reed Sheppard", "position": "G", "height": "6-3", "weight": "187 lbs", "last_attended": "Kentucky", "country": "USA"},
            {"name": "Cam Whitmore", "position": "F", "height": "6-6", "weight": "235 lbs", "last_attended": "Villanova", "country": "USA"},
        ]
    },
    {
        "id": 12,
        "name": "Indiana Pacers",
        "roster": [
            {"name": "Tony Bradley", "position": "C-F", "height": "6-10", "weight": "248 lbs", "last_attended": "North Carolina", "country": "USA"},
            {"name": "RayJ Dennis", "position": "G", "height": "6-1", "weight": "180 lbs", "last_attended": "Baylor", "country": "USA"},
            {"name": "Johnny Furphy", "position": "G", "height": "6-8", "weight": "200 lbs", "last_attended": "Kansas", "country": "Australia"},
            {"name": "Tyrese Haliburton", "position": "G", "height": "6-5", "weight": "185 lbs", "last_attended": "Iowa State", "country": "USA"},
            {"name": "Jay Huff", "position": "C", "height": "7-1", "weight": "240 lbs", "last_attended": "Virginia", "country": "USA"},
            {"name": "Isaiah Jackson", "position": "F", "height": "6-8", "weight": "205 lbs", "last_attended": "Kentucky", "country": "USA"},
            {"name": "Quenton Jackson", "position": "G", "height": "6-4", "weight": "173 lbs", "last_attended": "Texas A&M", "country": "USA"},
            {"name": "Kam Jones", "position": "G", "height": "6-4", "weight": "200 lbs", "last_attended": "Marquette", "country": "USA"},
            {"name": "Cody Martin", "position": "F", "height": "6-6", "weight": "205 lbs", "last_attended": "Nevada", "country": "USA"},
            {"name": "Bennedict Mathurin", "position": "G-F", "height": "6-5", "weight": "210 lbs", "last_attended": "Arizona", "country": "Canada"},
            {"name": "T.J. McConnell", "position": "G", "height": "6-1", "weight": "190 lbs", "last_attended": "Arizona", "country": "USA"},
            {"name": "Monté Morris", "position": "G", "height": "6-2", "weight": "183 lbs", "last_attended": "Iowa State", "country": "USA"},
            {"name": "Andrew Nembhard", "position": "G-F", "height": "6-4", "weight": "191 lbs", "last_attended": "Gonzaga", "country": "Canada"},
            {"name": "Aaron Nesmith", "position": "G-F", "height": "6-5", "weight": "215 lbs", "last_attended": "Vanderbilt", "country": "USA"},
            {"name": "Taelon Peter", "position": "G", "height": "6-3", "weight": "185 lbs", "last_attended": "Liberty", "country": "USA"},
            {"name": "Jeremiah Robinson-Earl", "position": "F", "height": "6-9", "weight": "240 lbs", "last_attended": "Villanova", "country": "USA"},
            {"name": "Ben Sheppard", "position": "G", "height": "6-6", "weight": "190 lbs", "last_attended": "Belmont", "country": "USA"},
            {"name": "Pascal Siakam", "position": "F", "height": "6-8", "weight": "245 lbs", "last_attended": "New Mexico State", "country": "Cameroon"},
            {"name": "Obi Toppin", "position": "F", "height": "6-9", "weight": "220 lbs", "last_attended": "Dayton", "country": "USA"},
            {"name": "Myles Turner", "position": "C-F", "height": "6-11", "weight": "250 lbs", "last_attended": "Texas", "country": "USA"},
        ]
    },
    {
        "id": 13,
        "name": "Los Angeles Clippers",
        "roster": [
            {"name": "Nicolas Batum", "position": "G-F", "height": "6-7", "weight": "230 lbs", "last_attended": "Le Mans", "country": "France"},
            {"name": "Bradley Beal", "position": "G", "height": "6-4", "weight": "207 lbs", "last_attended": "Florida", "country": "USA"},
            {"name": "Bogdan Bogdanović", "position": "G", "height": "6-5", "weight": "225 lbs", "last_attended": "Fenerbahce", "country": "Serbia"},
            {"name": "Kobe Brown", "position": "F", "height": "6-7", "weight": "250 lbs", "last_attended": "Missouri", "country": "USA"},
            {"name": "Cam Christie", "position": "G", "height": "6-5", "weight": "190 lbs", "last_attended": "Minnesota", "country": "USA"},
            {"name": "John Collins", "position": "F-C", "height": "6-9", "weight": "226 lbs", "last_attended": "Wake Forest", "country": "USA"},
            {"name": "Kris Dunn", "position": "G", "height": "6-3", "weight": "205 lbs", "last_attended": "Providence", "country": "USA"},
            {"name": "James Harden", "position": "G", "height": "6-5", "weight": "220 lbs", "last_attended": "Arizona State", "country": "USA"},
            {"name": "Derrick Jones Jr.", "position": "F", "height": "6-6", "weight": "210 lbs", "last_attended": "UNLV", "country": "USA"},
            {"name": "Kawhi Leonard", "position": "F", "height": "6-6", "weight": "225 lbs", "last_attended": "San Diego State", "country": "USA"},
            {"name": "Brook Lopez", "position": "C", "height": "7-1", "weight": "282 lbs", "last_attended": "Stanford", "country": "USA"},
            {"name": "Jordan Miller", "position": "G", "height": "6-5", "weight": "194 lbs", "last_attended": "Miami", "country": "USA"},
            {"name": "Yanic Konan Niederhäuser", "position": "C", "height": "6-11", "weight": "242 lbs", "last_attended": "Penn State", "country": "Switzerland"},
            {"name": "Chris Paul", "position": "G", "height": "6-0", "weight": "175 lbs", "last_attended": "Wake Forest", "country": "USA"},
            {"name": "Kobe Sanders", "position": "G", "height": "6-8", "weight": "207 lbs", "last_attended": "Nevada", "country": "USA"},
            {"name": "Jahmyl Telfort", "position": "G", "height": "6-7", "weight": "-", "last_attended": "-", "country": "Canada"},
            {"name": "Ivica Zubac", "position": "C", "height": "7-0", "weight": "240 lbs", "last_attended": "Mega Basket", "country": "Croatia"},
        ]
    },
    {
        "id": 14,
        "name": "Los Angeles Lakers",
        "roster": [
            {"name": "Deandre Ayton", "position": "C", "height": "7-0", "weight": "252 lbs", "last_attended": "Arizona", "country": "Bahamas"},
            {"name": "Luka Dončić", "position": "F-G", "height": "6-8", "weight": "230 lbs", "last_attended": "Real Madrid", "country": "Slovenia"},
            {"name": "Rui Hachimura", "position": "F", "height": "6-8", "weight": "230 lbs", "last_attended": "Gonzaga", "country": "Japan"},
            {"name": "Jaxson Hayes", "position": "C-F", "height": "7-0", "weight": "220 lbs", "last_attended": "Texas", "country": "USA"},
            {"name": "Bronny James", "position": "G", "height": "6-2", "weight": "210 lbs", "last_attended": "Southern California", "country": "USA"},
            {"name": "LeBron James", "position": "F", "height": "6-9", "weight": "250 lbs", "last_attended": "St. Vincent-St. Mary HS (OH)", "country": "USA"},
            {"name": "Maxi Kleber", "position": "F", "height": "6-10", "weight": "240 lbs", "last_attended": "Bayern Munich", "country": "Germany"},
            {"name": "Dalton Knecht", "position": "F", "height": "6-6", "weight": "215 lbs", "last_attended": "Tennessee", "country": "USA"},
            {"name": "Christian Koloko", "position": "C-F", "height": "6-11", "weight": "225 lbs", "last_attended": "Arizona", "country": "Cameroon"},
            {"name": "Jake LaRavia", "position": "F", "height": "6-7", "weight": "235 lbs", "last_attended": "Wake Forest", "country": "USA"},
            {"name": "Chris Mañon", "position": "G", "height": "6-4", "weight": "209 lbs", "last_attended": "Vanderbilt", "country": "USA"},
            {"name": "Austin Reaves", "position": "G", "height": "6-5", "weight": "197 lbs", "last_attended": "Oklahoma", "country": "USA"},
            {"name": "Marcus Smart", "position": "G", "height": "6-3", "weight": "220 lbs", "last_attended": "Oklahoma State", "country": "USA"},
            {"name": "Nick Smith Jr.", "position": "G", "height": "6-2", "weight": "185 lbs", "last_attended": "Arkansas", "country": "USA"},
            {"name": "Adou Thiero", "position": "G", "height": "6-7", "weight": "220 lbs", "last_attended": "Arkansas", "country": "USA"},
            {"name": "Jarred Vanderbilt", "position": "F", "height": "6-8", "weight": "214 lbs", "last_attended": "Kentucky", "country": "USA"},
            {"name": "Gabe Vincent", "position": "G", "height": "6-2", "weight": "200 lbs", "last_attended": "California-Santa Barbara", "country": "USA"},
        ]
    },
    {
        "id": 15,
        "name": "Memphis Grizzlies",
        "roster": [
            {"name": "Santi Aldama", "position": "F-C", "height": "7-0", "weight": "215 lbs", "last_attended": "Loyola-Maryland", "country": "Spain"},
            {"name": "Kentavious Caldwell-Pope", "position": "G", "height": "6-5", "weight": "204 lbs", "last_attended": "Georgia", "country": "USA"},
            {"name": "Brandon Clarke", "position": "F", "height": "6-8", "weight": "215 lbs", "last_attended": "Gonzaga", "country": "Canada"},
            {"name": "Cedric Coward", "position": "G", "height": "6-5", "weight": "206 lbs", "last_attended": "Washington State", "country": "USA"},
            {"name": "Zach Edey", "position": "C", "height": "7-3", "weight": "305 lbs", "last_attended": "Purdue", "country": "Canada"},
            {"name": "PJ Hall", "position": "C", "height": "6-8", "weight": "245 lbs", "last_attended": "Clemson", "country": "USA"},
            {"name": "GG Jackson", "position": "F", "height": "6-9", "weight": "210 lbs", "last_attended": "South Carolina", "country": "USA"},
            {"name": "Jaren Jackson Jr.", "position": "F-C", "height": "6-10", "weight": "242 lbs", "last_attended": "Michigan State", "country": "USA"},
            {"name": "Ty Jerome", "position": "G-F", "height": "6-5", "weight": "195 lbs", "last_attended": "Virginia", "country": "USA"},
            {"name": "John Konchar", "position": "G", "height": "6-5", "weight": "210 lbs", "last_attended": "Indiana-Purdue Fort Wayne", "country": "USA"},
            {"name": "Jock Landale", "position": "C", "height": "6-11", "weight": "255 lbs", "last_attended": "St. Mary's", "country": "Australia"},
            {"name": "Ja Morant", "position": "G", "height": "6-2", "weight": "174 lbs", "last_attended": "Murray State", "country": "USA"},
            {"name": "Scotty Pippen Jr.", "position": "G", "height": "6-2", "weight": "170 lbs", "last_attended": "Vanderbilt", "country": "USA"},
            {"name": "Olivier-Maxence Prosper", "position": "F", "height": "6-7", "weight": "230 lbs", "last_attended": "Marquette", "country": "Canada"},
            {"name": "Javon Small", "position": "G", "height": "6-1", "weight": "190 lbs", "last_attended": "West Virginia", "country": "USA"},
            {"name": "Cam Spencer", "position": "G", "height": "6-3", "weight": "205 lbs", "last_attended": "Connecticut", "country": "USA"},
            {"name": "Jaylen Wells", "position": "F", "height": "6-7", "weight": "-", "last_attended": "Washington State", "country": "USA"},
            {"name": "Vince Williams Jr.", "position": "G", "height": "6-4", "weight": "205 lbs", "last_attended": "Virginia Commonwealth", "country": "USA"},
        ]
    },
    {
        "id": 16,
        "name": "Miami Heat",
        "roster": [
            {"name": "Bam Adebayo", "position": "C-F", "height": "6-9", "weight": "255 lbs", "last_attended": "Kentucky", "country": "USA"},
            {"name": "Simone Fontecchio", "position": "F", "height": "6-7", "weight": "209 lbs", "last_attended": "Baskonia", "country": "Italy"},
            {"name": "Myron Gardner", "position": "F", "height": "6-5", "weight": "220 lbs", "last_attended": "Arkansas-Little Rock", "country": "USA"},
            {"name": "Vladislav Goldin", "position": "C", "height": "7-0", "weight": "250 lbs", "last_attended": "Michigan", "country": "Russia"},
            {"name": "Tyler Herro", "position": "G", "height": "6-5", "weight": "195 lbs", "last_attended": "Kentucky", "country": "USA"},
            {"name": "Kasparas Jakučionis", "position": "G", "height": "6-5", "weight": "200 lbs", "last_attended": "Illinois-Urbana-Champaign", "country": "Lithuania"},
            {"name": "Jaime Jaquez Jr.", "position": "G", "height": "6-6", "weight": "225 lbs", "last_attended": "UCLA", "country": "USA"},
            {"name": "Keshad Johnson", "position": "F", "height": "6-6", "weight": "225 lbs", "last_attended": "Arizona", "country": "USA"},
            {"name": "Nikola Jović", "position": "F", "height": "6-10", "weight": "205 lbs", "last_attended": "Mega Basket", "country": "Serbia"},
            {"name": "Pelle Larsson", "position": "G", "height": "6-5", "weight": "215 lbs", "last_attended": "Arizona", "country": "Sweden"},
            {"name": "Davion Mitchell", "position": "G", "height": "6-0", "weight": "202 lbs", "last_attended": "Baylor", "country": "USA"},
            {"name": "Norman Powell", "position": "G", "height": "6-3", "weight": "215 lbs", "last_attended": "UCLA", "country": "USA"},
            {"name": "Terry Rozier", "position": "G", "height": "6-1", "weight": "190 lbs", "last_attended": "Louisville", "country": "USA"},
            {"name": "Dru Smith", "position": "G", "height": "6-2", "weight": "203 lbs", "last_attended": "Missouri", "country": "USA"},
            {"name": "Kel'el Ware", "position": "C", "height": "7-0", "weight": "230 lbs", "last_attended": "Indiana", "country": "USA"},
            {"name": "Andrew Wiggins", "position": "F", "height": "6-6", "weight": "197 lbs", "last_attended": "Kansas", "country": "Canada"},
            {"name": "Jahmir Young", "position": "G", "height": "6-0", "weight": "185 lbs", "last_attended": "Maryland", "country": "USA"},
        ]
    },
    {
        "id": 17,
        "name": "Milwaukee Bucks",
        "roster": [
            {"name": "Alex Antetokounmpo", "position": "F", "height": "6-8", "weight": "214 lbs", "last_attended": "Greece", "country": "Greece"},
            {"name": "Giannis Antetokounmpo", "position": "F", "height": "6-11", "weight": "243 lbs", "last_attended": "Filathlitikos", "country": "Greece"},
            {"name": "Thanasis Antetokounmpo", "position": "F", "height": "6-7", "weight": "219 lbs", "last_attended": "Panathinaikos", "country": "Greece"},
            {"name": "Cole Anthony", "position": "G", "height": "6-2", "weight": "185 lbs", "last_attended": "North Carolina", "country": "USA"},
            {"name": "Amir Coffey", "position": "G-F", "height": "6-7", "weight": "210 lbs", "last_attended": "Minnesota", "country": "USA"},
            {"name": "AJ Green", "position": "G", "height": "6-4", "weight": "190 lbs", "last_attended": "Northern Iowa", "country": "USA"},
            {"name": "Gary Harris", "position": "G", "height": "6-4", "weight": "210 lbs", "last_attended": "Michigan State", "country": "USA"},
            {"name": "Andre Jackson Jr.", "position": "G", "height": "6-6", "weight": "209 lbs", "last_attended": "Connecticut", "country": "USA"},
            {"name": "Kyle Kuzma", "position": "F", "height": "6-8", "weight": "221 lbs", "last_attended": "Utah", "country": "USA"},
            {"name": "Pete Nance", "position": "F", "height": "6-9", "weight": "225 lbs", "last_attended": "Northwestern", "country": "USA"},
            {"name": "Kevin Porter Jr.", "position": "G-F", "height": "6-5", "weight": "203 lbs", "last_attended": "Southern California", "country": "USA"},
            {"name": "Bobby Portis", "position": "F", "height": "6-9", "weight": "250 lbs", "last_attended": "Arkansas", "country": "USA"},
            {"name": "Taurean Prince", "position": "F", "height": "6-6", "weight": "218 lbs", "last_attended": "Baylor", "country": "USA"},
            {"name": "Ryan Rollins", "position": "G", "height": "6-3", "weight": "180 lbs", "last_attended": "Toledo", "country": "USA"},
            {"name": "Mark Sears", "position": "G", "height": "6-0", "weight": "185 lbs", "last_attended": "Alabama", "country": "USA"},
            {"name": "Jericho Sims", "position": "C", "height": "6-10", "weight": "250 lbs", "last_attended": "Texas", "country": "USA"},
            {"name": "Gary Trent Jr.", "position": "G", "height": "6-5", "weight": "204 lbs", "last_attended": "Duke", "country": "USA"},
            {"name": "Myles Turner", "position": "C-F", "height": "6-11", "weight": "250 lbs", "last_attended": "Texas", "country": "USA"},
        ]
    },
    {
        "id": 18,
        "name": "Minnesota Timberwolves",
        "roster": [
            {"name": "Anthony Edwards", "position": "G", "height": "6-4", "weight": "225 lbs", "last_attended": "Georgia", "country": "USA"},
            {"name": "Rudy Gobert", "position": "C", "height": "7-1", "weight": "258 lbs", "last_attended": "Cholet", "country": "France"},
            {"name": "Julius Randle", "position": "F-C", "height": "6-8", "weight": "250 lbs", "last_attended": "Kentucky", "country": "USA"},
            {"name": "Jaden McDaniels", "position": "F", "height": "6-9", "weight": "185 lbs", "last_attended": "Washington", "country": "USA"},
            {"name": "Naz Reid", "position": "C-F", "height": "6-9", "weight": "264 lbs", "last_attended": "Louisiana State", "country": "USA"},
            {"name": "Mike Conley", "position": "G", "height": "6-0", "weight": "175 lbs", "last_attended": "Ohio State", "country": "USA"},
            {"name": "Nickeil Alexander-Walker", "position": "G", "height": "6-5", "weight": "205 lbs", "last_attended": "Virginia Tech", "country": "Canada"},
            {"name": "Donte DiVincenzo", "position": "G", "height": "6-4", "weight": "203 lbs", "last_attended": "Villanova", "country": "USA"},
            {"name": "Rob Dillingham", "position": "G", "height": "6-2", "weight": "175 lbs", "last_attended": "Kentucky", "country": "USA"},
        ]
    },
    {
        "id": 19,
        "name": "New Orleans Pelicans",
        "roster": [
            {"name": "Zion Williamson", "position": "F", "height": "6-6", "weight": "284 lbs", "last_attended": "Duke", "country": "USA"},
            {"name": "Brandon Ingram", "position": "F", "height": "6-8", "weight": "190 lbs", "last_attended": "Duke", "country": "USA"},
            {"name": "Dejounte Murray", "position": "G", "height": "6-4", "weight": "180 lbs", "last_attended": "Washington", "country": "USA"},
            {"name": "CJ McCollum", "position": "G", "height": "6-3", "weight": "190 lbs", "last_attended": "Lehigh", "country": "USA"},
            {"name": "Herbert Jones", "position": "F-G", "height": "6-7", "weight": "206 lbs", "last_attended": "Alabama", "country": "USA"},
            {"name": "Trey Murphy III", "position": "F", "height": "6-8", "weight": "206 lbs", "last_attended": "Virginia", "country": "USA"},
            {"name": "Daniel Theis", "position": "C-F", "height": "6-8", "weight": "245 lbs", "last_attended": "Ratiopharm Ulm", "country": "Germany"},
            {"name": "Jordan Hawkins", "position": "G", "height": "6-4", "weight": "185 lbs", "last_attended": "Connecticut", "country": "USA"},
            {"name": "Yves Missi", "position": "C", "height": "6-11", "weight": "230 lbs", "last_attended": "Baylor", "country": "Cameroon"},
        ]
    },
    {
        "id": 20,
        "name": "New York Knicks",
        "roster": [
            {"name": "OG Anunoby", "position": "F-G", "height": "6-7", "weight": "240 lbs", "last_attended": "Indiana", "country": "United Kingdom"},
            {"name": "Mikal Bridges", "position": "G-F", "height": "6-6", "weight": "209 lbs", "last_attended": "Villanova", "country": "USA"},
            {"name": "Jalen Brunson", "position": "G", "height": "6-2", "weight": "190 lbs", "last_attended": "Villanova", "country": "USA"},
            {"name": "Jordan Clarkson", "position": "G", "height": "6-5", "weight": "194 lbs", "last_attended": "Missouri", "country": "USA"},
            {"name": "Pacôme Dadiet", "position": "F", "height": "6-9", "weight": "210 lbs", "last_attended": "Ratiopharm Ulm", "country": "France"},
            {"name": "Mohamed Diawara", "position": "F", "height": "6-9", "weight": "225 lbs", "last_attended": "-", "country": "France"},
            {"name": "Tosan Evbuomwan", "position": "F", "height": "6-8", "weight": "217 lbs", "last_attended": "Princeton", "country": "United Kingdom"},
            {"name": "Josh Hart", "position": "G", "height": "6-5", "weight": "215 lbs", "last_attended": "Villanova", "country": "USA"},
            {"name": "Ariel Hukporti", "position": "C", "height": "7-0", "weight": "246 lbs", "last_attended": "Riesen Ludwigsburg", "country": "Germany"},
            {"name": "Trey Jemison III", "position": "C", "height": "6-10", "weight": "270 lbs", "last_attended": "Alabama-Birmingham", "country": "USA"},
            {"name": "Tyler Kolek", "position": "G", "height": "6-2", "weight": "195 lbs", "last_attended": "Marquette", "country": "USA"},
            {"name": "Miles McBride", "position": "G", "height": "6-2", "weight": "195 lbs", "last_attended": "West Virginia", "country": "USA"},
            {"name": "Kevin McCullar Jr.", "position": "G", "height": "6-6", "weight": "210 lbs", "last_attended": "Kansas", "country": "USA"},
            {"name": "Mitchell Robinson", "position": "C-F", "height": "7-0", "weight": "240 lbs", "last_attended": "Western Kentucky", "country": "USA"},
            {"name": "Landry Shamet", "position": "G", "height": "6-5", "weight": "190 lbs", "last_attended": "Wichita State", "country": "USA"},
            {"name": "Karl-Anthony Towns", "position": "C-F", "height": "7-0", "weight": "248 lbs", "last_attended": "Kentucky", "country": "USA"},
            {"name": "Guerschon Yabusele", "position": "F", "height": "6-7", "weight": "265 lbs", "last_attended": "Rouen, France", "country": "France"},
        ]
    },
    {
        "id": 21,
        "name": "Oklahoma City Thunder",
        "roster": [
            {"name": "Shai Gilgeous-Alexander", "position": "G", "height": "6-6", "weight": "195 lbs", "last_attended": "Kentucky", "country": "Canada"},
            {"name": "Chet Holmgren", "position": "C-F", "height": "7-0", "weight": "195 lbs", "last_attended": "Gonzaga", "country": "USA"},
            {"name": "Jalen Williams", "position": "F", "height": "6-6", "weight": "195 lbs", "last_attended": "Santa Clara", "country": "USA"},
            {"name": "Lu Dort", "position": "G", "height": "6-3", "weight": "220 lbs", "last_attended": "Arizona State", "country": "Canada"},
            {"name": "Cason Wallace", "position": "G", "height": "6-4", "weight": "193 lbs", "last_attended": "Kentucky", "country": "USA"},
            {"name": "Isaiah Hartenstein", "position": "C", "height": "7-0", "weight": "250 lbs", "last_attended": "Oregon", "country": "Germany"},
            {"name": "Alex Caruso", "position": "G", "height": "6-5", "weight": "186 lbs", "last_attended": "Texas A&M", "country": "USA"},
            {"name": "Isaiah Joe", "position": "G", "height": "6-4", "weight": "165 lbs", "last_attended": "Arkansas", "country": "USA"},
            {"name": "Ajay Mitchell", "position": "G", "height": "6-4", "weight": "205 lbs", "last_attended": "California-Santa Barbara", "country": "USA"},
            {"name": "Aaron Wiggins", "position": "G-F", "height": "6-5", "weight": "190 lbs", "last_attended": "Maryland", "country": "USA"},
        ]
    },
    {
        "id": 22,
        "name": "Orlando Magic",
        "roster": [
            {"name": "Paolo Banchero", "position": "F", "height": "6-10", "weight": "250 lbs", "last_attended": "Duke", "country": "USA"},
            {"name": "Desmond Bane", "position": "G", "height": "6-6", "weight": "215 lbs", "last_attended": "TCU", "country": "USA"},
            {"name": "Goga Bitadze", "position": "C-F", "height": "6-11", "weight": "250 lbs", "last_attended": "Mega Basket", "country": "Georgia"},
            {"name": "Anthony Black", "position": "G", "height": "6-7", "weight": "200 lbs", "last_attended": "Arkansas", "country": "USA"},
            {"name": "Jamal Cain", "position": "F", "height": "6-7", "weight": "191 lbs", "last_attended": "Oakland", "country": "USA"},
            {"name": "Wendell Carter Jr.", "position": "C-F", "height": "6-10", "weight": "270 lbs", "last_attended": "Duke", "country": "USA"},
            {"name": "Colin Castleton", "position": "C", "height": "6-10", "weight": "250 lbs", "last_attended": "Florida", "country": "USA"},
            {"name": "Tristan da Silva", "position": "F", "height": "6-8", "weight": "217 lbs", "last_attended": "Colorado", "country": "Germany"},
            {"name": "Jett Howard", "position": "G", "height": "6-8", "weight": "215 lbs", "last_attended": "Michigan", "country": "USA"},
            {"name": "Jonathan Isaac", "position": "F", "height": "6-10", "weight": "230 lbs", "last_attended": "Florida State", "country": "USA"},
            {"name": "Tyus Jones", "position": "G", "height": "6-0", "weight": "196 lbs", "last_attended": "Duke", "country": "USA"},
            {"name": "Noah Penda", "position": "G-F", "height": "6-7", "weight": "215 lbs", "last_attended": "-", "country": "France"},
            {"name": "Jase Richardson", "position": "G", "height": "6-1", "weight": "180 lbs", "last_attended": "Michigan State", "country": "USA"},
            {"name": "Orlando Robinson", "position": "C", "height": "6-10", "weight": "235 lbs", "last_attended": "Fresno State", "country": "USA"},
            {"name": "Jalen Suggs", "position": "G", "height": "6-5", "weight": "205 lbs", "last_attended": "Gonzaga", "country": "USA"},
            {"name": "Franz Wagner", "position": "F", "height": "6-10", "weight": "220 lbs", "last_attended": "Michigan", "country": "Germany"},
            {"name": "Moritz Wagner", "position": "F-C", "height": "6-11", "weight": "245 lbs", "last_attended": "Michigan", "country": "Germany"},
        ]
    },
    {
        "id": 23,
        "name": "Philadelphia 76ers",
        "roster": [
            {"name": "Dominick Barlow", "position": "F", "height": "6-9", "weight": "215 lbs", "last_attended": "Overtime Elite", "country": "USA"},
            {"name": "Adem Bona", "position": "F", "height": "6-10", "weight": "235 lbs", "last_attended": "UCLA", "country": "Nigeria"},
            {"name": "Johni Broome", "position": "F", "height": "6-10", "weight": "235 lbs", "last_attended": "Auburn", "country": "USA"},
            {"name": "Andre Drummond", "position": "C", "height": "6-11", "weight": "279 lbs", "last_attended": "Connecticut", "country": "USA"},
            {"name": "VJ Edgecombe", "position": "G", "height": "6-4", "weight": "180 lbs", "last_attended": "Baylor", "country": "USA"},
            {"name": "Justin Edwards", "position": "F", "height": "6-7", "weight": "203 lbs", "last_attended": "Kentucky", "country": "USA"},
            {"name": "Joel Embiid", "position": "C-F", "height": "7-0", "weight": "280 lbs", "last_attended": "Kansas", "country": "Cameroon"},
            {"name": "Paul George", "position": "F", "height": "6-8", "weight": "220 lbs", "last_attended": "Fresno State", "country": "USA"},
            {"name": "Eric Gordon", "position": "G", "height": "6-3", "weight": "215 lbs", "last_attended": "Indiana", "country": "USA"},
            {"name": "Quentin Grimes", "position": "G", "height": "6-4", "weight": "210 lbs", "last_attended": "Houston", "country": "USA"},
            {"name": "Kyle Lowry", "position": "G", "height": "6-0", "weight": "196 lbs", "last_attended": "Villanova", "country": "USA"},
            {"name": "Tyrese Maxey", "position": "G", "height": "6-2", "weight": "200 lbs", "last_attended": "Kentucky", "country": "USA"},
            {"name": "Jared McCain", "position": "G", "height": "6-3", "weight": "195 lbs", "last_attended": "Duke", "country": "USA"},
            {"name": "Kelly Oubre Jr.", "position": "F-G", "height": "6-8", "weight": "203 lbs", "last_attended": "Kansas", "country": "USA"},
            {"name": "Hunter Sallis", "position": "G", "height": "6-4", "weight": "185 lbs", "last_attended": "Wake Forest", "country": "USA"},
            {"name": "Jabari Walker", "position": "F", "height": "6-7", "weight": "237 lbs", "last_attended": "Colorado", "country": "USA"},
            {"name": "Trendon Watford", "position": "G-F", "height": "6-8", "weight": "237 lbs", "last_attended": "Louisiana State", "country": "USA"},
        ]
    },
    {
        "id": 24,
        "name": "Phoenix Suns",
        "roster": [
            {"name": "Kevin Durant", "position": "F", "height": "6-10", "weight": "240 lbs", "last_attended": "Texas", "country": "USA"},
            {"name": "Devin Booker", "position": "G", "height": "6-5", "weight": "206 lbs", "last_attended": "Kentucky", "country": "USA"},
            {"name": "Bradley Beal", "position": "G", "height": "6-4", "weight": "207 lbs", "last_attended": "Florida", "country": "USA"},
            {"name": "Jusuf Nurkić", "position": "C", "height": "6-11", "weight": "290 lbs", "last_attended": "Cedevita", "country": "Bosnia and Herzegovina"},
            {"name": "Tyus Jones", "position": "G", "height": "6-0", "weight": "196 lbs", "last_attended": "Duke", "country": "USA"},
            {"name": "Grayson Allen", "position": "G", "height": "6-4", "weight": "198 lbs", "last_attended": "Duke", "country": "USA"},
            {"name": "Royce O'Neale", "position": "F", "height": "6-4", "weight": "226 lbs", "last_attended": "Baylor", "country": "USA"},
            {"name": "Mason Plumlee", "position": "F-C", "height": "7-0", "weight": "254 lbs", "last_attended": "Duke", "country": "USA"},
            {"name": "Ryan Dunn", "position": "F", "height": "6-6", "weight": "213 lbs", "last_attended": "Virginia", "country": "USA"},
        ]
    },
    {
        "id": 25,
        "name": "Portland Trail Blazers",
        "roster": [
            {"name": "Anfernee Simons", "position": "G", "height": "6-3", "weight": "200 lbs", "last_attended": "Edgewater HS (FL)", "country": "USA"},
            {"name": "Jerami Grant", "position": "F", "height": "6-7", "weight": "210 lbs", "last_attended": "Syracuse", "country": "USA"},
            {"name": "Deandre Ayton", "position": "C", "height": "7-0", "weight": "252 lbs", "last_attended": "Arizona", "country": "Bahamas"},
            {"name": "Scoot Henderson", "position": "G", "height": "6-2", "weight": "195 lbs", "last_attended": "NBA G League Ignite", "country": "USA"},
            {"name": "Shaedon Sharpe", "position": "G", "height": "6-5", "weight": "200 lbs", "last_attended": "Kentucky", "country": "Canada"},
            {"name": "Donovan Clingan", "position": "C", "height": "7-2", "weight": "280 lbs", "last_attended": "Connecticut", "country": "USA"},
            {"name": "Deni Avdija", "position": "F", "height": "6-9", "weight": "225 lbs", "last_attended": "Maccabi Tel Aviv", "country": "Israel"},
            {"name": "Toumani Camara", "position": "F", "height": "6-8", "weight": "220 lbs", "last_attended": "Dayton", "country": "Belgium"},
            {"name": "Robert Williams III", "position": "C-F", "height": "6-9", "weight": "237 lbs", "last_attended": "Texas A&M", "country": "USA"},
        ]
    },
    {
        "id": 26,
        "name": "Sacramento Kings",
        "roster": [
            {"name": "Precious Achiuwa", "position": "F", "height": "6-8", "weight": "243 lbs", "last_attended": "Memphis", "country": "Nigeria"},
            {"name": "Dylan Cardwell", "position": "C", "height": "6-10", "weight": "255 lbs", "last_attended": "Auburn", "country": "USA"},
            {"name": "Devin Carter", "position": "G", "height": "6-2", "weight": "195 lbs", "last_attended": "Providence", "country": "USA"},
            {"name": "Nique Clifford", "position": "G", "height": "6-5", "weight": "175 lbs", "last_attended": "Colorado State", "country": "USA"},
            {"name": "DeMar DeRozan", "position": "G-F", "height": "6-6", "weight": "220 lbs", "last_attended": "Southern California", "country": "USA"},
            {"name": "Keon Ellis", "position": "G", "height": "6-4", "weight": "175 lbs", "last_attended": "Alabama", "country": "USA"},
            {"name": "Drew Eubanks", "position": "F-C", "height": "6-10", "weight": "245 lbs", "last_attended": "Oregon State", "country": "USA"},
            {"name": "Zach LaVine", "position": "G", "height": "6-5", "weight": "200 lbs", "last_attended": "UCLA", "country": "USA"},
            {"name": "Doug McDermott", "position": "F", "height": "6-7", "weight": "225 lbs", "last_attended": "Creighton", "country": "USA"},
            {"name": "Malik Monk", "position": "G", "height": "6-3", "weight": "200 lbs", "last_attended": "Kentucky", "country": "USA"},
            {"name": "Keegan Murray", "position": "F", "height": "6-8", "weight": "225 lbs", "last_attended": "Iowa", "country": "USA"},
            {"name": "Daeqwon Plowden", "position": "G-F", "height": "6-4", "weight": "216 lbs", "last_attended": "Bowling Green", "country": "USA"},
            {"name": "Maxime Raynaud", "position": "C", "height": "7-1", "weight": "250 lbs", "last_attended": "Stanford", "country": "France"},
            {"name": "Domantas Sabonis", "position": "F-C", "height": "6-10", "weight": "240 lbs", "last_attended": "Gonzaga", "country": "Lithuania"},
            {"name": "Dario Šarić", "position": "F-C", "height": "6-10", "weight": "225 lbs", "last_attended": "Anadolu Efes", "country": "Croatia"},
            {"name": "Dennis Schröder", "position": "G", "height": "6-1", "weight": "175 lbs", "last_attended": "Braunschweig", "country": "Germany"},
            {"name": "Isaiah Stevens", "position": "G", "height": "5-11", "weight": "185 lbs", "last_attended": "Colorado State", "country": "USA"},
            {"name": "Russell Westbrook", "position": "G", "height": "6-4", "weight": "200 lbs", "last_attended": "UCLA", "country": "USA"},
        ]
    },
    {
        "id": 27,
        "name": "San Antonio Spurs",
        "roster": [
            {"name": "Victor Wembanyama", "position": "C-F", "height": "7-4", "weight": "210 lbs", "last_attended": "Metropolitans 92", "country": "France"},
            {"name": "Chris Paul", "position": "G", "height": "6-0", "weight": "175 lbs", "last_attended": "Wake Forest", "country": "USA"},
            {"name": "Harrison Barnes", "position": "F", "height": "6-8", "weight": "225 lbs", "last_attended": "North Carolina", "country": "USA"},
            {"name": "Devin Vassell", "position": "G-F", "height": "6-5", "weight": "200 lbs", "last_attended": "Florida State", "country": "USA"},
            {"name": "Jeremy Sochan", "position": "F", "height": "6-8", "weight": "230 lbs", "last_attended": "Baylor", "country": "Poland"},
            {"name": "Keldon Johnson", "position": "F", "height": "6-5", "weight": "220 lbs", "last_attended": "Kentucky", "country": "USA"},
            {"name": "Tre Jones", "position": "G", "height": "6-1", "weight": "185 lbs", "last_attended": "Duke", "country": "USA"},
            {"name": "Stephon Castle", "position": "G", "height": "6-6", "weight": "215 lbs", "last_attended": "Connecticut", "country": "USA"},
            {"name": "Zach Collins", "position": "F-C", "height": "6-9", "weight": "250 lbs", "last_attended": "Gonzaga", "country": "USA"},
        ]
    },
    {
        "id": 28,
        "name": "Toronto Raptors",
        "roster": [
            {"name": "Scottie Barnes", "position": "F", "height": "6-7", "weight": "225 lbs", "last_attended": "Florida State", "country": "USA"},
            {"name": "RJ Barrett", "position": "F", "height": "6-6", "weight": "214 lbs", "last_attended": "Duke", "country": "Canada"},
            {"name": "Jakob Poeltl", "position": "C", "height": "7-1", "weight": "245 lbs", "last_attended": "Utah", "country": "Austria"},
            {"name": "Immanuel Quickley", "position": "G", "height": "6-3", "weight": "188 lbs", "last_attended": "Kentucky", "country": "USA"},
            {"name": "Gradey Dick", "position": "G-F", "height": "6-6", "weight": "205 lbs", "last_attended": "Kansas", "country": "Canada"},
            {"name": "Ochai Agbaji", "position": "G", "height": "6-5", "weight": "215 lbs", "last_attended": "Kansas", "country": "USA"},
            {"name": "Bruce Brown", "position": "G-F", "height": "6-4", "weight": "202 lbs", "last_attended": "Miami", "country": "USA"},
            {"name": "Kelly Olynyk", "position": "F-C", "height": "6-11", "weight": "240 lbs", "last_attended": "Gonzaga", "country": "Canada"},
            {"name": "Ja'Kobe Walter", "position": "G", "height": "6-4", "weight": "197 lbs", "last_attended": "Baylor", "country": "USA"},
        ]
    },
    {
        "id": 29,
        "name": "Utah Jazz",
        "roster": [
            {"name": "Kyle Anderson", "position": "F-G", "height": "6-8", "weight": "230 lbs", "last_attended": "UCLA", "country": "USA"},
            {"name": "Ace Bailey", "position": "F", "height": "6-9", "weight": "200 lbs", "last_attended": "Rutgers", "country": "USA"},
            {"name": "Walter Clayton Jr.", "position": "G", "height": "6-4", "weight": "195 lbs", "last_attended": "Florida", "country": "USA"},
            {"name": "Isaiah Collier", "position": "G", "height": "6-4", "weight": "210 lbs", "last_attended": "Southern California", "country": "USA"},
            {"name": "Kyle Filipowski", "position": "C", "height": "6-11", "weight": "250 lbs", "last_attended": "Duke", "country": "USA"},
            {"name": "Keyonte George", "position": "G", "height": "6-4", "weight": "185 lbs", "last_attended": "Baylor", "country": "USA"},
            {"name": "Elijah Harkless", "position": "G", "height": "6-3", "weight": "195 lbs", "last_attended": "UNLV", "country": "USA"},
            {"name": "Taylor Hendricks", "position": "F", "height": "6-9", "weight": "215 lbs", "last_attended": "Central Florida", "country": "USA"},
            {"name": "Walker Kessler", "position": "C", "height": "7-2", "weight": "245 lbs", "last_attended": "Auburn", "country": "USA"},
            {"name": "Kevin Love", "position": "F-C", "height": "6-10", "weight": "251 lbs", "last_attended": "UCLA", "country": "USA"},
            {"name": "Lauri Markkanen", "position": "F-C", "height": "7-1", "weight": "240 lbs", "last_attended": "Arizona", "country": "Finland"},
            {"name": "Svi Mykhailiuk", "position": "G-F", "height": "6-7", "weight": "205 lbs", "last_attended": "Kansas", "country": "Ukraine"},
            {"name": "Georges Niang", "position": "F", "height": "6-6", "weight": "230 lbs", "last_attended": "Iowa State", "country": "USA"},
            {"name": "Jusuf Nurkić", "position": "C", "height": "6-11", "weight": "290 lbs", "last_attended": "Cedevita", "country": "Bosnia and Herzegovina"},
            {"name": "Brice Sensabaugh", "position": "F", "height": "6-6", "weight": "235 lbs", "last_attended": "Ohio State", "country": "USA"},
            {"name": "John Tonje", "position": "G", "height": "6-4", "weight": "218 lbs", "last_attended": "Wisconsin", "country": "USA"},
            {"name": "Oscar Tshiebwe", "position": "F-C", "height": "6-8", "weight": "255 lbs", "last_attended": "Kentucky", "country": "DRC"},
            {"name": "Cody Williams", "position": "F", "height": "6-8", "weight": "190 lbs", "last_attended": "Colorado", "country": "USA"},
        ]
    },
    {
        "id": 30,
        "name": "Washington Wizards",
        "roster": [
            {"name": "Jordan Poole", "position": "G", "height": "6-4", "weight": "194 lbs", "last_attended": "Michigan", "country": "USA"},
            {"name": "Kyle Kuzma", "position": "F", "height": "6-8", "weight": "221 lbs", "last_attended": "Utah", "country": "USA"},
            {"name": "Alex Sarr", "position": "C-F", "height": "7-0", "weight": "224 lbs", "last_attended": "Perth Wildcats", "country": "France"},
            {"name": "Bilal Coulibaly", "position": "G-F", "height": "6-6", "weight": "195 lbs", "last_attended": "Metropolitans 92", "country": "France"},
            {"name": "Corey Kispert", "position": "F-G", "height": "6-6", "weight": "220 lbs", "last_attended": "Gonzaga", "country": "USA"},
            {"name": "Bub Carrington", "position": "G", "height": "6-4", "weight": "185 lbs", "last_attended": "Pittsburgh", "country": "USA"},
            {"name": "Jonas Valančiūnas", "position": "C", "height": "6-11", "weight": "265 lbs", "last_attended": "Lietuvos rytas Vilnius", "country": "Lithuania"},
            {"name": "Kyshawn George", "position": "F", "height": "6-7", "weight": "210 lbs", "last_attended": "Miami", "country": "Switzerland"},
            {"name": "Carlton Carrington", "position": "G", "height": "6-4", "weight": "195 lbs", "last_attended": "Pittsburgh", "country": "USA"},
        ]
    }
]
